name: ci
on:
  push:
    branches: [aliyun-fc3-test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build:aliyun-fc3-test

      - name: Setup @serverless-devs/s
        run: npx s config add -a hono-aliyun-fc3 --AccessKeyID ${{ secrets.ALIYUN_FC3_DEPLOY_KEY_ID }} --AccessKeySecret ${{ secrets.ALIYUN_FC3_DEPLOY_KEY_SECRET }} -f

      - name: Deploy
        run: yarn run deploy:aliyun-fc3-test

      - name: Curl endpoint
        run: curl ${{ secrets.ALIYUN_FC3_ENDPOINT }}
